config/routes.rb
Rails.application.routes.draw do
  get 'activity/mine'

  get 'activity/feed'
  root to: 'bathrooms#index'
  resources :comments
  resources :locations
  resources :bathroom_locations
  resources :bathrooms
  resources :users
  get "/signup", to: "users#new", as: "signup"
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bathroom.rb
class Bathroom < ApplicationRecord
  has_many :bathroom_locations
  has_many :locations, through: :bathroom_locations
  has_many :comments
  has_many :users, through: :comments
  accepts_nested_attributes_for :locations


  def cleanest_bathroom
      hash = {}
      Bathroom.all.map do |bathroom|
         hash[bathroom.name] = bathroom.cleanliness
      end
      a=hash.sort_by {|_key, value| value}.last
      "#{a[0]} with a rating of #{a[1]}!"
  end

  def dirtiest_bathroom
    hash = {}
    Bathroom.all.map do |bathroom|
       hash[bathroom.name] = bathroom.cleanliness
    end
    a=hash.sort_by {|_key, value| value}.first
    "#{a[0]} with a rating of #{a[1]}!"
  end


  def most_comments
    #Look through all of the bathrooms
    #Count the number of comments for each bathroom
    #Which bathroom has the most comments
    hash = {}
    Bathroom.all.map do |bathroom|
      hash[bathroom.name] = bathroom.comments.count
    end
    a=hash.sort_by {|_key, value| value}.last
    "#{a[0]} has the most comments with #{a[1]}!"
  end



end

app/models/bathroom_location.rb
class BathroomLocation < ApplicationRecord
  belongs_to :bathroom
  belongs_to :location
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :bathroom
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :bathroom_locations
  has_many :bathrooms, through: :bathroom_locations


 def bathroom_count
    "Number of Bathrooms: #{self.bathrooms.count}"
 end


 def average_rating
   self.bathrooms.average(:cleanliness)
 end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :bathrooms, through: :comments
  has_secure_password
  validates :username, presence: true, uniqueness: true


  def bathrooms_reviewed
    "Number of Bathrooms Reviewed: #{self.bathrooms.count}"
  end

  def number_of_comments
    "Number of Comments: #{self.comments.count}"
  end

end

app/controllers/activity_controller.rb
class ActivityController < ApplicationController
  def mine
  end

  def feed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authorized



  helper_method :logged_in?


  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    else
    end
  end


  def logged_in?
     !!current_user
  end




  def authorized
    redirect_to login_path unless logged_in?
  end
end

app/controllers/bathrooms_controller.rb
class BathroomsController < ApplicationController
  def index
    @bathrooms = Bathroom.all

    #@bathrooms = current_user.bathrooms
  end

  def new
   @bathroom = Bathroom.new
   @locations = Location.all
  end

  def show
   @bathroom = Bathroom.find(params[:id])
  end

  def create
   @bathroom = Bathroom.new(bathroom_params)
   if @bathroom.valid?
     @bathroom.save
     redirect_to @bathroom
   else
    flash[:error] = @bathroom.errors.full_messages
    redirect_to new_bathroom_path
   end
  end

  def edit
    @bathroom = Bathroom.find(params[:id])
    @locations = Location.all
  end

  def update
    @bathroom = Bathroom.find(params[:id])
    if @bathroom.update(bathroom_params)
      redirect_to @bathroom
    else
     flash[:error] = @bathroom.errors.full_messages
     redirect_to edit_bathroom_path
    end
   end

  def destroy
    @bathroom = Bathroom.find(params[:id])
    @bathroom.destroy
    redirect_to bathrooms_path
  end


  private

    def bathroom_params
      params.require(:bathroom).permit(:name, :cleanliness, location_ids: [], locations_attributes: [:neighborhood])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def new
   @comment = Comment.new
   @users = User.all
   @bathrooms = Bathroom.all
  end

  def show
   @comment = Comment.find(params[:id])
  end

  def create
   @comment = Comment.new(comment_params)
   if @comment.valid?
     @comment.save
     redirect_to @comment
   else
    flash[:error] = @comment.errors.full_messages
    redirect_to new_comment_path
   end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.new(comment_params)
    if @comment.valid?
      @comment.save
      redirect_to @comment
    else
     flash[:error] = @comment.errors.full_messages
     redirect_to edit_comment_path
    end
   end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to comments_path
  end


  private

  def comment_params
    params.require(:comment).permit(:content, :user_id, :bathroom_id)
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end

  def new
    @location = Location.new
  end

  def show
    @location = Location.find(params[:id])
  end

  def create
    @location = Location.new(location_params)
    if @location.valid?
      @location.save
      redirect_to location_path(@location)
    else
      flash[:error] = @location.errors.full_messages
      redirect_to new_location_path
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    if @location.update(location_params)
      redirect_to @location
    else
     flash[:error] = @location.errors.full_messages
     redirect_to edit_location_path
    end
   end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to locations_path
  end

 private

  def location_params
    params.require(:location).permit(:neighborhood)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
  end

  def create

    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      #This needs to be adjusted!!!!!!!!!! I dont have a User ID!!!!
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else

      flash[:error] = ["Username and password do not match"]
      redirect_to login_path
    end
  end


  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    if logged_in?
      flash[:msg] = "Welcome #{current_user.username}"
    else
    end
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end


  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bathroom_locations_helper.rb
module BathroomLocationsHelper
end

app/helpers/bathrooms_helper.rb
module BathroomsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activity/feed.html.erb
<h1>Activity#feed</h1>
<p>Find me in app/views/activity/feed.html.erb</p>

app/views/activity/mine.html.erb
<h1>Activity#mine</h1>
<p>Find me in app/views/activity/mine.html.erb</p>

app/views/bathrooms/edit.html.erb
<ul>
  <% if flash[:error] %>
  <% flash[:error].each do |error| %>
  <li><%= error %> </li>
  <% end %>
  <% end %>

</ul>

<%= form_for @bathroom do |f| %>
<%= f.label :name %>
<%= f.text_field :name, placeholder: "Name of Bathroom" %>

<%= f.label :cleanliness %>
<%= f.text_field :cleanliness, placeholder: "Rate from 1-10" %>

<%= f.collection_check_boxes :location_ids, @locations, :id, :neighborhood %>
<%= f.submit %>

<% end %>

app/views/bathrooms/index.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li class="active"><%= link_to 'Bathrooms', bathrooms_path %></li>
  <li><%= link_to 'View Comments', comments_path %></li>
  <li><%= link_to 'View Locations', locations_path %></li>
  <li><%= link_to 'View Users', users_path %></li>
</ul>

<h2>Bathrooms and Ratings</h2>
<% @bathrooms.each do |bathroom| %>
  <p><%= link_to bathroom.name, bathroom, class: 'btn btn-success'%>: <%= bathroom.cleanliness %></p>
<% end %>

<%= link_to new_bathroom_path, class: 'btn btn-warning' do %>
  <i class="glyphicon glyphicon-plus"></i> Create Bathroom
<% end %>

app/views/bathrooms/new.html.erb
<ul>
  <% if flash[:error] %>
  <% flash[:error].each do |error| %>
  <li><%= error %> </li>
  <% end %>
  <% end %>

</ul>

#####Need to add feature so only users can create bathrooms
<%= form_for @bathroom do |f| %>
<%= f.label :name %>
<%= f.text_field :name, placeholder: "Name of Bathroom" %>

<%= f.label :cleanliness %>
<%= f.text_field :cleanliness, placeholder: "Rate from 1-10" %><br>

<%= f.collection_check_boxes :location_ids, @locations, :id, :neighborhood %><br>
<%= f.fields_for :locations, @bathroom.locations.build do |locations_fields| %>
    <%= locations_fields.text_field :neighborhood, placeholder: "Write a Neighborhood" %>
  <% end %>
<%= f.submit %>

<% end %>

app/views/bathrooms/show.html.erb
<h1><%= @bathroom.name %> -  Cleanliness: <%= @bathroom.cleanliness %></h1>

<ul>
  <p>Location:</p>
  <% @bathroom.locations.each do |location| %>
  <li><%= link_to location.neighborhood, location %></li>
  <% end %>
</ul>

<ul>
  <p>Comments:</p>
  <% @bathroom.comments.each do |comment| %>
  <li>User: <%= link_to comment.user.username, comment.user %>: <%= link_to comment.content, comment %></li>
  <% end %>
</ul><br>

<h4>Cleanest Bathroom</h4>
<p><%= @bathroom.cleanest_bathroom %></p><br>

<h4>Dirtiest Bathroom</h4>
<p><%= @bathroom.dirtiest_bathroom %></p><br>

<h4>Most Comments</h4>
<p><%= @bathroom.most_comments %></p><br>

<%= link_to new_comment_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> Create Comment
<% end %>

<%= link_to 'Delete Bathroom', bathroom_path(@bathroom), method: :delete, class: 'btn btn-danger'  %>
<%= link_to 'Edit Bathroom', edit_bathroom_path(@bathroom), class: 'btn btn-warning'  %><br>

app/views/comments/index.html.erb
<h3>Bathroom Comments:</h3>
<ul>
  <% @comments.each do |comment| %>
  <li> <%= link_to comment.bathroom.name, comment.bathroom, class: 'btn btn-info' %> - <%= link_to comment.content, comment, class: 'btn btn-success' %></li>
  <% end %>
</ul>

app/views/comments/new.html.erb
<ul>
  <% if flash[:error] %>
  <% flash[:error].each do |error| %>
  <li><%= error %> </li>
  <% end %>
  <% end %>

</ul>

<%= form_for @comment do |f| %>
<%= f.label :content %>
<%= f.text_field :content %>


<%= f.collection_select :user_id, @users, :id, :username %>
<%= f.collection_select :bathroom_id, @bathrooms, :id, :name %>

<%= f.submit %>

<% end %>

app/views/comments/show.html.erb
<h2>Comment: </h2>

<ul>
  <li>User: <%= link_to @comment.user.username, @comment.user %> |
    Bathroom: <%= link_to @comment.bathroom.name, @comment.bathroom %>
    | Comment: <%= @comment.content %></li>
</ul>

<td><%= link_to 'All Comments', comments_path, class: 'btn btn-info' %></td>
<%= link_to 'Delete Comment', comment_path(@comment), method: :delete, class: 'btn btn-danger'  %><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PublicPortaPotty</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navigation' %>
    <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-3">
          <h4>Find a Bathroom!</h4>
          <p><%= link_to 'View Bathrooms', bathrooms_path %></p>
          <p><%= link_to 'View Locations', locations_path %></p>
          <h4>Add a Bathroom!</h4>
          <p><%= link_to 'Create a Bathroom', new_bathroom_path %></p>
          <p><%= link_to 'Create a Location', new_location_path %></p>
          <p><%= link_to 'Create a Comment', new_comment_path %></p>
        </div>
        <div class="col-xs-9">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/locations/edit.html.erb
<%= form_for @location do |f| %>

<%= f.label :neighborhood %>
<%= f.text_field :neighborhood %>

<%= f.submit %>

<% end %>

app/views/locations/index.html.erb
<h2>Locations</h2>
<% @locations.each do |location| %>
  <p><%= link_to location.neighborhood, location, class: 'btn btn-success' %> - <%= location.bathroom_count %></p>
<% end %>

<%= link_to new_location_path, class: 'btn btn-warning' do %>
  <i class="glyphicon glyphicon-plus"></i> Create Location
<% end %>

app/views/locations/new.html.erb
<%= form_for @location do |f| %>

<%= f.label :neighborhood %>
<%= f.text_field :neighborhood %>

<%= f.submit %>

<% end %>

app/views/locations/show.html.erb
<h1><%= @location.neighborhood %></h1>

<ul>
  <% @location.bathrooms.each do |bathroom| %>
  <li><%= link_to bathroom.name, bathroom %></li>
  <% end %> <br>

  <h3> Average Rating: <%= @location.average_rating %></h3>
</ul>

<%= link_to new_bathroom_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> Create Bathroom

  <%= link_to 'Delete Location', location_path(@location), method: :delete, class: 'btn btn-danger'  %>
  <%= link_to 'Edit Location', edit_location_path(@location), class: 'btn btn-warning'  %><br>
<% end %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Public Porta Potty</a>
    </div>

    <ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li class="divider"></li>
      <li><%= link_to 'Signup', signup_path %></li>
      <li><%= link_to 'Login', login_path %></li>
      <li><%= link_to 'View Bathrooms', bathrooms_path %></li>
      <li><%= link_to 'View Locations', locations_path %></li>
    </ul>
  </li>
</ul>
  </div>
</nav>

app/views/users/_form.html.erb
<ul>
  <% if flash[:error] %>
  <% flash[:error].each do |error| %>
  <li><%= error %> </li>
  <% end %>
  <% end %>

</ul>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username, placeholder: "Username" %>
  <%= f.password_field :password, placeholder: "Password" %>
  <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h2>All Users</h2>
<ul>
  <% @users.each do |user| %>
     <li><%= link_to user.username, user, class: 'btn btn-success' %> |
        <%= user.bathrooms_reviewed %> |
     <%= user.number_of_comments %></li><br>
   <%end %>
</ul>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

Bathroom's Reviewed:
<ul>
  <% @user.bathrooms.each do |bathroom| %>
  <li><%= link_to bathroom.name, bathroom %></li>
  <% end %>
</ul>


Comments:
<ul>
  <% @user.comments.each do |comment| %>
  <li><%= link_to comment.content, comment %></li>
  <% end %>
</ul>

<td><%= link_to 'New Bathroom', new_bathroom_path, class: 'btn btn-primary btn-xs' %></td>
<td><%= link_to 'All Bathrooms', bathrooms_path, class: 'btn btn-primary btn-xs' %></td>